version: '2.4'
networks:
  mqtt: {}
services:
  emqx:
    image: 'emqx/emqx:latest'
    ports:
      - '80:18083'
      - '1883:1883'
      - '11883:11883'
      - '8883:8883'
      - '8083:8083'
      - '8084:8084'
    networks:
      - mqtt
  neuron:
    image: 'emqx/neuron:latest'
    ports:
      - '7000:7000'
    restart: always
    privileged: true
  data-generators:
    build:
      context: .
      dockerfile: generator_simulator/Dockerfile.template
    networks:
      - mqtt
    depends_on:
      - emqx
    environment:
      BROKER: emqx
      GENERATORS: '3'